require 'what-input'
require 'picturefill'
require '_fastclick'
require '_navigation'
require '_twitter'
require '_formsubmit'
require '_map'
require '_consolidate'
require '_focusparent'
require '_menu-icon'
require '_animations'
require '_video'
require '_scroll'

# require '_scroll-indicator'
# require '_typed'
# require '_transition'
# require '_lazyload'
# require '_fonts'
